### ISSUE TITLE
Research how to perform the synchronization

### ISSUE THREAD

**Issue by Right2Drive** [WeSyncVideo/wesync-web#1]
## Previous Solution

1) `socket.io` was used for signaling between the host and client. This required a signal server to be running
2) `simplepeer` was used to create a p2p WebRTC connection between the two
3) 'captureStream` Chrome API was used to send a stream of the video from the host to the client
4) All commands (pause, play, seek, etc) were sent from the client to the host over this WebRTC connection

## Problems

- This API is experimental on Firefox and must be enabled via a flag
- Did not allow for buffering to occur

## Benefits

- Works for all video tags that are not protected via DRM. This means we could create an extension to tie into the API

## Alternatives

- WebTorrent & WebRTC could be used to sync the video, and would allow buffering to occur, and would be supported on all major browsers

**Comment by RationalCoding** [comment]
`mozCaptureStream` is available without a flag so long as your source isn't from a WebRTC MediaStream (which I think will be the case most of the time).

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream

**Comment by RationalCoding** [comment]
If you do go ahead with an extension, it is relatively simple to do screen capture as well.

**Comment by Right2Drive** [comment]
Will be using the captureStream (& mozCaptureStream if it works for the use case) alongside Webtorrent
